import numpy as np

AUDIO_SAMPLE_RATE = 44100
FFT_HOP = 256
CONTOURS_BINS_PER_SEMITONE = 3
N_HARMONICS = 7
ANNOTATIONS_BASE_FREQUENCY = 27.5  # Lowest key on a piano
ANNOTATIONS_N_SEMITONES = 88  # Number of piano keys
MAX_N_SEMITONES = int(np.floor(12.0 * np.log2(0.5 * AUDIO_SAMPLE_RATE / ANNOTATIONS_BASE_FREQUENCY)))

EVAL_TOLERANCE = 0.05
OCTAVE_INVARIANT_RADIUS = 16
N_FFT = 1024